name: Build Jasypt Java Wrapper
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: |
          cd java
          mvn clean package
      
      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v2
        with:
          name: jasypt-wrapper
          path: java/target/jasypt-wrapper.jar