name: Build Jasypt Java Wrapper

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin

      - name: Build with Maven
        run: |
          mvn -f java/pom.xml clean package
          echo ":: Listing target directory"
          ls -la java/target

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@main
        with:
          name: jasypt-wrapper
          path: java/target/jasypt-wrapper.jar
