name: Build Jasypt Java Wrapper

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin  # Required field

      # Step 3: Build with Maven and generate the JAR
      - name: Build with Maven
        run: |
          mvn -f java/pom.xml clean package
          echo ":: Listing target directory"
          ls -la java/target

      # Step 4: Upload JAR as artifact
      - name: Upload JAR as artifact
        uses: actions/upload-artifact@main
        with:
          name: jasypt-wrapper
          path: java/target/jasypt-wrapper.jar
